language: c

before_script:
  - gcc --version
  - cd 1_datalab
  - make clean
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - make clean

stages:
  - compliance
  - grade

jobs:
  include:
    - stage: compliance
      script: ./dlc bits.c
    - stage: grade
      script: ./btest
