language: c

after_success:
  - bash <(curl -s https://codecov.io/bash)

stages:
  - build
  - compliance
  - grade

jobs:
  include:
    - stage: build
      script:
        - cd 1_datalab
        - make clean
        - make
    - stage: compliance
      script: ./dlc bits.c
    - stage: grade
      script: ./btest
