language: c

before_script:
  - gcc --version

after_success:
  - make clean

stages:
  - 1_autograding
  - 1_coverage
  - 4_build
  - 4_leak_check
  - 4_autograding

jobs:
  include:
    - stage: 1_autograding
      script: 
        - cd 1_datalab
        - make clean
        - make
        - ./btest
    - stage: 1_coverage
      script:
        - cd 1_datalab
        - make clean
        - make
        - gcc -coverage -O0 -Wall -lm -o btest bits.c btest.c decl.c tests.c
        - ./btest
        - gcov bits.c
        - bash <(curl -s https://codecov.io/bash)
    - stage: 4_build
      script:
        - cd 4_cachelab
        - make clean
        - make
    - stage: 4_leak_check
      script:
        - cd 4_cachelab
        - make clean
        - make
        - valgrind --leak-resolution=high --leak-check=full --show-reachable=yes --track-fds=yes ./csim -v -s 3 -E 8 -b 2 -t "traces/dave.trace"
    - stage: 4_autograding
      script:
        - cd 4_cachelab
        - make clean
        - make
        - ./test-csim
    