language: c

before_script:
  - gcc --version
  - cd 1_datalab
  - make clean
  - make

after_success:
  - make clean

stages:
  - compliance
  - grade
  - coverage

jobs:
  allow_failures:
    - if: branch = master
  include:
    - stage: compliance
      script: ./dlc bits.c
    - stage: grade
      script: ./btest
    - stage: coverage
      script:
        - clang -coverage -O0 btest.c -o btest
        - ./btest
        - gcov btest.c
        - bash <(curl -s https://codecov.io/bash)
