language: c
os: linux
dist: xenial

before_script:
  - gcc --version

after_success:
  - make clean

stages:
  - 1_datalab:autograding
  - 1_datalab:coverage
  - 2_bomblab:autograding
  - 3_attacklab:autograding
  - 4_cachelab:build
  - 4_cachelab:leak_check
  - 4_cachelab:autograding
  - 5_shlab:build
  - 5_shlab:leak_check

jobs:
  include:
    - stage: 1_datalab:autograding
      script: 
        - cd 1_datalab
        - make clean
        - make
        - ./btest
    - stage: 1_datalab:coverage
      script:
        - cd 1_datalab
        - make clean
        - make
        - gcc -coverage -O0 -Wall -lm -o btest bits.c btest.c decl.c tests.c
        - ./btest
        - gcov bits.c
        - bash <(curl -s https://codecov.io/bash)
    - stage: 2_bomblab:autograding
      script:
        - cd 2_bomblab
        - ./bomb phrase.txt
    - stage: 3_attacklab:autograding
      script:
        - cd 3_attacklab
        - ./hex2raw < cp1.txt >cp1_o.txt
        - ./ctarget -qi cp1_o.txt
        - ./hex2raw < cp2.txt >cp2_o.txt
        - ./ctarget -qi cp2_o.txt
        - ./hex2raw < cp3.txt >cp3_o.txt
        - ./ctarget -qi cp3_o.txt
        - ./hex2raw < rp4.txt >rp4_o.txt
        - ./rtarget -qi rp4_o.txt
        - ./hex2raw < rp5.txt >rp5_o.txt
        - ./rtarget -qi rp5_o.txt
    - stage: 4_cachelab:build
      script:
        - cd 4_cachelab
        - make clean
        - make
    - stage: 4_cachelab:leak_check
      script:
        - cd 4_cachelab
        - make clean
        - make
        - sudo apt-get install valgrind
        - valgrind --leak-resolution=high --leak-check=full --show-reachable=yes --track-fds=yes ./csim -v -s 4 -E 1 -b 4 -t "traces/dave.trace"
    - stage: 4_cachelab:autograding
      script:
        - cd 4_cachelab
        - make clean
        - make
        - sudo apt-get install valgrind
        - ./driver.py
    - stage: 5_shlab:build
      script:
        - cd 5_shlab
        - make clean
        - make
    - stage: 5_shlab:leak_check
      script:
        - cd 5_shlab
        - make clean
        - make
        - sudo apt-get install valgrind
        - valgrind --leak-resolution=high --leak-check=full --show-reachable=yes --track-fds=yes ./sdriver.pl -t trace01.txt -s ./tsh -a "-p"
        # - valgrind --leak-resolution=high --leak-check=full --show-reachable=yes --track-fds=yes ./sdriver.pl -t trace02.txt -s ./tsh -a "-p"
        # - valgrind --leak-resolution=high --leak-check=full --show-reachable=yes --track-fds=yes ./sdriver.pl -t trace03.txt -s ./tsh -a "-p"
        # - valgrind --leak-resolution=high --leak-check=full --show-reachable=yes --track-fds=yes ./sdriver.pl -t trace04.txt -s ./tsh -a "-p"
        # - valgrind --leak-resolution=high --leak-check=full --show-reachable=yes --track-fds=yes ./sdriver.pl -t trace05.txt -s ./tsh -a "-p"
        # - valgrind --leak-resolution=high --leak-check=full --show-reachable=yes --track-fds=yes ./sdriver.pl -t trace06.txt -s ./tsh -a "-p"
        # - valgrind --leak-resolution=high --leak-check=full --show-reachable=yes --track-fds=yes ./sdriver.pl -t trace07.txt -s ./tsh -a "-p"
        # - valgrind --leak-resolution=high --leak-check=full --show-reachable=yes --track-fds=yes ./sdriver.pl -t trace08.txt -s ./tsh -a "-p"
        # - valgrind --leak-resolution=high --leak-check=full --show-reachable=yes --track-fds=yes ./sdriver.pl -t trace09.txt -s ./tsh -a "-p"
        # - valgrind --leak-resolution=high --leak-check=full --show-reachable=yes --track-fds=yes ./sdriver.pl -t trace010.txt -s ./tsh -a "-p"
        # - valgrind --leak-resolution=high --leak-check=full --show-reachable=yes --track-fds=yes ./sdriver.pl -t trace011.txt -s ./tsh -a "-p"
        # - valgrind --leak-resolution=high --leak-check=full --show-reachable=yes --track-fds=yes ./sdriver.pl -t trace012.txt -s ./tsh -a "-p"
        # - valgrind --leak-resolution=high --leak-check=full --show-reachable=yes --track-fds=yes ./sdriver.pl -t trace013.txt -s ./tsh -a "-p"
        # - valgrind --leak-resolution=high --leak-check=full --show-reachable=yes --track-fds=yes ./sdriver.pl -t trace014.txt -s ./tsh -a "-p"
        # - valgrind --leak-resolution=high --leak-check=full --show-reachable=yes --track-fds=yes ./sdriver.pl -t trace015.txt -s ./tsh -a "-p"
        # - valgrind --leak-resolution=high --leak-check=full --show-reachable=yes --track-fds=yes ./sdriver.pl -t trace016.txt -s ./tsh -a "-p"

  